const toggle=document.getElementById('theme-toggle');function sync(){const light=document.documentElement.dataset.theme==='light';toggle.textContent=light?'☾':'☼';toggle.setAttribute('aria-label',light?'Switch to dark theme':'Switch to light theme')}sync();toggle.addEventListener('click',()=>{const next=document.documentElement.dataset.theme==='light'?'dark':'light';document.documentElement.dataset.theme=next;try{localStorage.setItem('portfolio-theme',next)}catch(e){}sync()});
const japanese={
'home':'ホーム','about':'自己紹介','skills':'スキル','projects':'プロジェクト','experience':'職歴','certifications':'資格','why me':'私の強み','contact':'連絡先',
'HELLO, I\'M':'はじめまして','Data Analyst':'データアナリスト','Dashboard Builder':'ダッシュボード制作者','Curious Problem Solver':'課題解決を楽しむ人',
'I turn messy data into clear insights and useful dashboards. I enjoy finding the human story behind the numbers and making it easier for teams to act on what they learn.':'複雑なデータを分かりやすい知見と使いやすいダッシュボードに変えます。数字の背景にいる人に目を向け、チームが次の行動を考えやすくすることを大切にしています。',
'View My Projects ↗':'プロジェクトを見る ↗','Contact Me':'お問い合わせ','Download CV ↓':'履歴書をダウンロード ↓','GitHub ↗':'GitHub ↗','LinkedIn ↗':'LinkedIn ↗',
'01 / ABOUT':'01 / 自己紹介','About me':'自己紹介',
'I’m a data analyst with a background in tourism, hospitality, and cross-cultural communication.':'観光、ホスピタリティ、異文化コミュニケーションを学び、データ分析に取り組んでいます。',
'At Ritsumeikan Asia Pacific University, I study Sustainability and Tourism. My analytical work combines Python, spreadsheets, visual storytelling, and conversations with stakeholders to make data understandable and useful.':'立命館アジア太平洋大学でサステイナビリティと観光を学んでいます。Python、表計算、可視化、関係者との対話を組み合わせ、データを理解しやすく実用的な形にまとめます。',
'During my internship, I built a member needs dashboard and presented insights and recommendations to the team.':'インターンシップでは、会員のニーズを把握するダッシュボードを作成し、分析結果と提案をチームに発表しました。',
'AT A GLANCE':'プロフィール','Focus':'専門分野','Data analysis & visualization':'データ分析・可視化','Education':'学歴','Ritsumeikan Asia Pacific University':'立命館アジア太平洋大学','Based in':'拠点','Japan':'日本','Interested in':'関心','People, patterns & practical decisions':'人、データの傾向、実務に役立つ判断',
'02 / SKILLS':'02 / スキル','What I work with':'主なスキル','Data analysis':'データ分析','Cleaning, exploration, text classification, reporting, and turning questions into measurable insights.':'データの整理、探索、テキストの分類、レポート作成を通じて、疑問を具体的な知見につなげます。','Dashboards':'ダッシュボード','Building clear views that help people explore findings and understand what matters.':'分析結果を探索し、大切なポイントを理解できる見やすい画面を作ります。','Communication':'コミュニケーション','Explaining results to mixed audiences and connecting findings to practical recommendations.':'さまざまな立場の人に結果を伝え、実行できる提案につなげます。','Storytelling':'ストーリーテリング','Presentations':'プレゼンテーション','Research':'リサーチ',
'03 / PROJECTS':'03 / プロジェクト','Selected projects':'主なプロジェクト','A few examples of how I use data to answer real questions.':'実際の課題にデータで取り組んだ事例を紹介します。','01 / INTERNSHIP PROJECT':'01 / インターンシップ','Member Needs Dashboard':'会員ニーズ・ダッシュボード',
'Organized member profile responses into meaningful categories and built an interactive Streamlit dashboard for exploring needs and interests. The work also included manual review of unclear responses and recommendations for the team.':'会員プロフィールの回答を分かりやすいカテゴリに整理し、ニーズや関心を探索できるStreamlitダッシュボードを作成しました。不明確な回答の確認や、チームへの提案も行いました。','Text classification':'テキスト分類','Project details are summarized without private member records or dashboard access.':'会員の個人情報や非公開ダッシュボードへのアクセスは掲載していません。',
'02 / CUSTOMER INSIGHTS':'02 / 顧客インサイト','Kyoto Hotel Guest Sentiment':'京都のホテル宿泊客レビュー分析','Analyzed hotel reviews to understand satisfaction drivers and compare guest experiences across hotel tiers. Presented the findings in an Excel dashboard.':'ホテルのレビューを分析し、満足度を左右する要因や価格帯による体験の違いを調べました。結果はExcelのダッシュボードにまとめました。','Sentiment analysis':'感情分析',
'03 / ANALYTICS':'03 / データ分析','Retail Sales Forecast':'小売売上予測','Explored sales trends, tracked key metrics, and built a monthly revenue forecast to support planning.':'売上の傾向と主な指標を分析し、計画に役立つ月次売上予測を作成しました。','Forecasting':'予測',
'04 / EXPERIENCE':'04 / 職歴','Where I’ve worked':'これまでの経験','Data Analyst Intern':'データアナリスト・インターン','Cleaned and categorized member data from CSV files, developed an interactive dashboard, and presented findings and recommendations.':'CSVデータを整理・分類し、操作できるダッシュボードを開発。分析結果と提案を発表しました。','World Ambassador':'ワールドアンバサダー','Beppu City Hall':'別府市役所','Facilitated global learning and English conversations with junior high school students.':'中学生との英語での対話や国際理解の学習をサポートしました。','Operations & Guest Experience Intern':'宿泊運営・ゲストサービス インターン','ANA Crowne Plaza Hotel Kobe':'ANAクラウンプラザホテル神戸','Supported guest service and learned how day-to-day customer experiences shape service decisions.':'ゲスト対応を支援し、日々の顧客体験がサービスの判断にどうつながるかを学びました。',
'05 / CERTIFICATIONS':'05 / 資格','Learning in progress':'学習・取得した資格','Data Analytics Basics':'データ分析の基礎','Analyzing Data with Excel':'Excelによるデータ分析','Data Visualization & Dashboards':'データ可視化とダッシュボード',
'06 / WHY ME':'06 / 私の強み','How I approach a project':'プロジェクトへの取り組み方','Start with the question':'課題から始める','I make sure the analysis answers something a team needs to understand or decide.':'チームが理解・判断したいことに分析が答えられるようにします。','Check the messy parts':'曖昧なデータを確認する','I review unclear responses and explain the choices behind my categories.':'不明確な回答を確認し、分類の基準を説明できるようにします。','Make results usable':'結果を使いやすくする','I turn findings into readable visuals and practical next steps.':'結果を分かりやすい図と実行できる次の一歩にまとめます。',
'07 / CONTACT':'07 / お問い合わせ','Let’s connect.':'お気軽にご連絡ください。','Interested in data analysis, dashboards, or a conversation about my work? I’d love to hear from you.':'データ分析やダッシュボード、これまでの取り組みにご関心があれば、ぜひご連絡ください。','Email Me ↗':'メールを送る ↗','Back to top ↑':'ページ上部へ ↑',
'clean and classify':'整理・分類','explore patterns':'傾向を探る','build dashboards':'ダッシュボードを作る','share insights':'知見を共有'
};
const nodes=[];const walker=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode(node){return node.parentElement?.closest('script,style')||!node.textContent.trim()?NodeFilter.FILTER_REJECT:NodeFilter.FILTER_ACCEPT}});while(walker.nextNode()){const node=walker.currentNode;nodes.push([node,node.textContent]);}
const languageToggle=document.getElementById('language-toggle');function renderLanguage(){const ja=document.documentElement.lang==='ja';for(const [node,original] of nodes){const key=original.trim();if(japanese[key])node.textContent=ja?original.replace(key,japanese[key]):original;}languageToggle.textContent=ja?'EN':'日本語';languageToggle.setAttribute('aria-label',ja?'Switch to English':'日本語に切り替える');document.title=ja?'Han Yu Kyaw | データアナリスト':'Han Yu Kyaw | Data Analyst'}renderLanguage();languageToggle.addEventListener('click',()=>{document.documentElement.lang=document.documentElement.lang==='ja'?'en':'ja';try{localStorage.setItem('portfolio-language',document.documentElement.lang)}catch(e){}renderLanguage()});
